#GAME SETTINGS
WIDTH = 900
HEIGHT = 600
FPS = 60

#DEFAULT FILES' PATHS
CROSSHAIR = 'assets/images/crosshair.png'

#CHARACTER CARDS
CARD_WIDTH = 150
CARD_HEIGHT = 215
STATUS_STRING_Y = 110

#ACTION FRAME
ACTION_X = 625
ACTION_Y = 45
ACTION_WIDTH = 235
ACTION_HEIGHT = 300
ACTIONS = ['Attack', 'Use Skill', 'Guard']

#ENEMIES SPRITES
EN_FRAME_WIDTH = ACTION_X
EN_FRAME_HEIGHT = HEIGHT - CARD_HEIGHT
EN_START_Y = EN_FRAME_HEIGHT // 3
