#GAME SETTINGS
WIDTH = 1024
HEIGHT = 600
FPS = 60

#DEFAULT FILES' PATHS
CROSSHAIR = 'assets/images/crosshair.png'

#ACTION FRAME
ACTION_SHIFT = 0.98
ACTION_WIDTH = 300
ACTION_HEIGHT = 275
ACTION_X = WIDTH * ACTION_SHIFT - ACTION_WIDTH
ACTION_Y = HEIGHT * ACTION_SHIFT - ACTION_HEIGHT
SP_COST_SHIFT = 0.95
ACTIONS = ['Attack', 'Use Skill', 'Guard', 'Escape']

#HINT_FRAME
HINT_X = ACTION_X
HINT_Y = 75
HINT_HEIGHT = (HEIGHT - ACTION_Y - 75) * 0.96
HINT_FONT_SIZE = 25
HINT_FONT_CORRECTIVE_K = 0.7

#CHARACTER CARDS
CARDS_AREA_WIDTH = WIDTH * ACTION_SHIFT - ACTION_WIDTH
CARD_WIDTH = 150
CARD_HEIGHT = 215
STATUS_STRING_Y = 110
CARD_SHIFT = 0.98

#ENEMIES SPRITES
EN_FRAME_WIDTH = WIDTH
EN_FRAME_HEIGHT = HEIGHT - CARD_HEIGHT
EN_START_Y = EN_FRAME_HEIGHT * 0.55
